# Generated by Django 3.1.7 on 2021-03-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='copy_location',
            new_name='location',
        ),
    ]
